---
#  _____                 _     _____                                 _ 
# |  ___|   __ _   ___  | |_  |_   _|  _ __    __ _  __   __   ___  | |
# | |_     / _` | / __| | __|   | |   | '__|  / _` | \ \ / /  / _ \ | |
# |  _|   | (_| | \__ \ | |_    | |   | |    | (_| |  \ V /  |  __/ | |
# |_|      \__,_| |___/  \__|   |_|   |_|     \__,_|   \_/    \___| |_|
#
# Travel in MCPE faster and easier than you ever tought !
#
# Author: Ad5001
# Website: http://github.com/Ad5001/FastTravel
#

# Put here the block you want to be an elevetor.
ElevatorBlock: note_block

SpeedBlock: ice
...